// packages/frontend/src/main.tsx
//
// React entry point. Pure plumbing: mount React, hand control to TanStack
// Router. There is no ProjectProject-specific logic here — every page lives in
// `src/routes/`, and `routeTree.gen.ts` is auto-generated by the router
// plugin during `vite dev`.
//
// You should not need to touch this file in Chapter 0.

import { RegistryContext } from "@effect-atom/atom-react"
import { StrictMode } from "react"
import ReactDOM from "react-dom/client"
import { createRouter, RouterProvider } from "@tanstack/react-router"
import { STATE_COLORS } from "@projectproject/shared"
import { RouteLoader } from "./components/Loader/RouteLoader"
import { registry } from "./runtime"
import { routeTree } from "./routeTree.gen"
import "./styles.css"

const stateColorStyle = document.createElement("style")
const lightStateVars = Object.entries(STATE_COLORS)
  .map(([name, c]) => `--state-${name}:${c.light.oklch};`)
  .join("")
const darkStateVars = Object.entries(STATE_COLORS)
  .map(([name, c]) => `--state-${name}:${c.dark.oklch};`)
  .join("")
stateColorStyle.textContent = `:root{${lightStateVars}}.dark{${darkStateVars}}`
document.head.appendChild(stateColorStyle)

const router = createRouter({
  routeTree,
  defaultPreload: "intent",
  defaultPendingComponent: RouteLoader,
  context: { registry }
})

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router
  }
}

const rootEl = document.getElementById("root")
if (!rootEl) throw new Error("Root element #root not found")

ReactDOM.createRoot(rootEl).render(
  <StrictMode>
    <RegistryContext.Provider value={registry}>
      <RouterProvider router={router} />
    </RegistryContext.Provider>
  </StrictMode>
)
