/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicOauthConsentRouteImport } from './routes/(public)/oauth.consent'
import { Route as AuthedOrgsOrgSlugRouteRouteImport } from './routes/_authed/orgs/$orgSlug/route'
import { Route as AuthedOrgsOrgSlugIndexRouteImport } from './routes/_authed/orgs/$orgSlug/index'
import { Route as AuthedOrgsOrgSlugProjectsIndexRouteImport } from './routes/_authed/orgs/$orgSlug/projects/index'
import { Route as AuthedOrgsOrgSlugProjectsSlugRouteRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/route'
import { Route as AuthedOrgsOrgSlugProjectsSlugIndexRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/index'
import { Route as AuthedOrgsOrgSlugProjectsSlugAboutRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/about'
import { Route as AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/sprints/route'
import { Route as AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/settings/route'
import { Route as AuthedOrgsOrgSlugProjectsSlugSprintsIndexRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/sprints/index'
import { Route as AuthedOrgsOrgSlugProjectsSlugSettingsIndexRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/settings/index'
import { Route as AuthedOrgsOrgSlugProjectsSlugTicketsIdRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/tickets/$id'
import { Route as AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/sprints/$groupId'
import { Route as AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/settings/workflow'
import { Route as AuthedOrgsOrgSlugProjectsSlugSettingsTeamRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/settings/team'
import { Route as AuthedOrgsOrgSlugProjectsSlugSettingsStatusesRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/settings/statuses'
import { Route as AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/settings/integrations'
import { Route as AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/settings/general'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const publicOauthConsentRoute = publicOauthConsentRouteImport.update({
  id: '/(public)/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOrgsOrgSlugRouteRoute = AuthedOrgsOrgSlugRouteRouteImport.update({
  id: '/orgs/$orgSlug',
  path: '/orgs/$orgSlug',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrgsOrgSlugIndexRoute = AuthedOrgsOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOrgsOrgSlugRouteRoute,
} as any)
const AuthedOrgsOrgSlugProjectsIndexRoute =
  AuthedOrgsOrgSlugProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthedOrgsOrgSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugRouteRoute =
  AuthedOrgsOrgSlugProjectsSlugRouteRouteImport.update({
    id: '/projects/$slug',
    path: '/projects/$slug',
    getParentRoute: () => AuthedOrgsOrgSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugIndexRoute =
  AuthedOrgsOrgSlugProjectsSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugAboutRoute =
  AuthedOrgsOrgSlugProjectsSlugAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSprintsRouteRoute =
  AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteImport.update({
    id: '/sprints',
    path: '/sprints',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute =
  AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSprintsIndexRoute =
  AuthedOrgsOrgSlugProjectsSlugSprintsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugSprintsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSettingsIndexRoute =
  AuthedOrgsOrgSlugProjectsSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugTicketsIdRoute =
  AuthedOrgsOrgSlugProjectsSlugTicketsIdRouteImport.update({
    id: '/tickets/$id',
    path: '/tickets/$id',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRoute =
  AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugSprintsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRoute =
  AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRouteImport.update({
    id: '/workflow',
    path: '/workflow',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSettingsTeamRoute =
  AuthedOrgsOrgSlugProjectsSlugSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSettingsStatusesRoute =
  AuthedOrgsOrgSlugProjectsSlugSettingsStatusesRouteImport.update({
    id: '/statuses',
    path: '/statuses',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRoute =
  AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRoute =
  AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/welcome': typeof WelcomeRoute
  '/login': typeof publicLoginRoute
  '/profile': typeof AuthedProfileRoute
  '/orgs/$orgSlug': typeof AuthedOrgsOrgSlugRouteRouteWithChildren
  '/oauth/consent': typeof publicOauthConsentRoute
  '/orgs/$orgSlug/': typeof AuthedOrgsOrgSlugIndexRoute
  '/orgs/$orgSlug/projects/$slug': typeof AuthedOrgsOrgSlugProjectsSlugRouteRouteWithChildren
  '/orgs/$orgSlug/projects/': typeof AuthedOrgsOrgSlugProjectsIndexRoute
  '/orgs/$orgSlug/projects/$slug/settings': typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteWithChildren
  '/orgs/$orgSlug/projects/$slug/sprints': typeof AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteWithChildren
  '/orgs/$orgSlug/projects/$slug/about': typeof AuthedOrgsOrgSlugProjectsSlugAboutRoute
  '/orgs/$orgSlug/projects/$slug/': typeof AuthedOrgsOrgSlugProjectsSlugIndexRoute
  '/orgs/$orgSlug/projects/$slug/settings/general': typeof AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRoute
  '/orgs/$orgSlug/projects/$slug/settings/integrations': typeof AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRoute
  '/orgs/$orgSlug/projects/$slug/settings/statuses': typeof AuthedOrgsOrgSlugProjectsSlugSettingsStatusesRoute
  '/orgs/$orgSlug/projects/$slug/settings/team': typeof AuthedOrgsOrgSlugProjectsSlugSettingsTeamRoute
  '/orgs/$orgSlug/projects/$slug/settings/workflow': typeof AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRoute
  '/orgs/$orgSlug/projects/$slug/sprints/$groupId': typeof AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRoute
  '/orgs/$orgSlug/projects/$slug/tickets/$id': typeof AuthedOrgsOrgSlugProjectsSlugTicketsIdRoute
  '/orgs/$orgSlug/projects/$slug/settings/': typeof AuthedOrgsOrgSlugProjectsSlugSettingsIndexRoute
  '/orgs/$orgSlug/projects/$slug/sprints/': typeof AuthedOrgsOrgSlugProjectsSlugSprintsIndexRoute
}
export interface FileRoutesByTo {
  '/welcome': typeof WelcomeRoute
  '/login': typeof publicLoginRoute
  '/profile': typeof AuthedProfileRoute
  '/': typeof AuthedIndexRoute
  '/oauth/consent': typeof publicOauthConsentRoute
  '/orgs/$orgSlug': typeof AuthedOrgsOrgSlugIndexRoute
  '/orgs/$orgSlug/projects': typeof AuthedOrgsOrgSlugProjectsIndexRoute
  '/orgs/$orgSlug/projects/$slug/about': typeof AuthedOrgsOrgSlugProjectsSlugAboutRoute
  '/orgs/$orgSlug/projects/$slug': typeof AuthedOrgsOrgSlugProjectsSlugIndexRoute
  '/orgs/$orgSlug/projects/$slug/settings/general': typeof AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRoute
  '/orgs/$orgSlug/projects/$slug/settings/integrations': typeof AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRoute
  '/orgs/$orgSlug/projects/$slug/settings/statuses': typeof AuthedOrgsOrgSlugProjectsSlugSettingsStatusesRoute
  '/orgs/$orgSlug/projects/$slug/settings/team': typeof AuthedOrgsOrgSlugProjectsSlugSettingsTeamRoute
  '/orgs/$orgSlug/projects/$slug/settings/workflow': typeof AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRoute
  '/orgs/$orgSlug/projects/$slug/sprints/$groupId': typeof AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRoute
  '/orgs/$orgSlug/projects/$slug/tickets/$id': typeof AuthedOrgsOrgSlugProjectsSlugTicketsIdRoute
  '/orgs/$orgSlug/projects/$slug/settings': typeof AuthedOrgsOrgSlugProjectsSlugSettingsIndexRoute
  '/orgs/$orgSlug/projects/$slug/sprints': typeof AuthedOrgsOrgSlugProjectsSlugSprintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/(public)/login': typeof publicLoginRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/orgs/$orgSlug': typeof AuthedOrgsOrgSlugRouteRouteWithChildren
  '/(public)/oauth/consent': typeof publicOauthConsentRoute
  '/_authed/orgs/$orgSlug/': typeof AuthedOrgsOrgSlugIndexRoute
  '/_authed/orgs/$orgSlug/projects/$slug': typeof AuthedOrgsOrgSlugProjectsSlugRouteRouteWithChildren
  '/_authed/orgs/$orgSlug/projects/': typeof AuthedOrgsOrgSlugProjectsIndexRoute
  '/_authed/orgs/$orgSlug/projects/$slug/settings': typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteWithChildren
  '/_authed/orgs/$orgSlug/projects/$slug/sprints': typeof AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteWithChildren
  '/_authed/orgs/$orgSlug/projects/$slug/about': typeof AuthedOrgsOrgSlugProjectsSlugAboutRoute
  '/_authed/orgs/$orgSlug/projects/$slug/': typeof AuthedOrgsOrgSlugProjectsSlugIndexRoute
  '/_authed/orgs/$orgSlug/projects/$slug/settings/general': typeof AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRoute
  '/_authed/orgs/$orgSlug/projects/$slug/settings/integrations': typeof AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRoute
  '/_authed/orgs/$orgSlug/projects/$slug/settings/statuses': typeof AuthedOrgsOrgSlugProjectsSlugSettingsStatusesRoute
  '/_authed/orgs/$orgSlug/projects/$slug/settings/team': typeof AuthedOrgsOrgSlugProjectsSlugSettingsTeamRoute
  '/_authed/orgs/$orgSlug/projects/$slug/settings/workflow': typeof AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRoute
  '/_authed/orgs/$orgSlug/projects/$slug/sprints/$groupId': typeof AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRoute
  '/_authed/orgs/$orgSlug/projects/$slug/tickets/$id': typeof AuthedOrgsOrgSlugProjectsSlugTicketsIdRoute
  '/_authed/orgs/$orgSlug/projects/$slug/settings/': typeof AuthedOrgsOrgSlugProjectsSlugSettingsIndexRoute
  '/_authed/orgs/$orgSlug/projects/$slug/sprints/': typeof AuthedOrgsOrgSlugProjectsSlugSprintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome'
    | '/login'
    | '/profile'
    | '/orgs/$orgSlug'
    | '/oauth/consent'
    | '/orgs/$orgSlug/'
    | '/orgs/$orgSlug/projects/$slug'
    | '/orgs/$orgSlug/projects/'
    | '/orgs/$orgSlug/projects/$slug/settings'
    | '/orgs/$orgSlug/projects/$slug/sprints'
    | '/orgs/$orgSlug/projects/$slug/about'
    | '/orgs/$orgSlug/projects/$slug/'
    | '/orgs/$orgSlug/projects/$slug/settings/general'
    | '/orgs/$orgSlug/projects/$slug/settings/integrations'
    | '/orgs/$orgSlug/projects/$slug/settings/statuses'
    | '/orgs/$orgSlug/projects/$slug/settings/team'
    | '/orgs/$orgSlug/projects/$slug/settings/workflow'
    | '/orgs/$orgSlug/projects/$slug/sprints/$groupId'
    | '/orgs/$orgSlug/projects/$slug/tickets/$id'
    | '/orgs/$orgSlug/projects/$slug/settings/'
    | '/orgs/$orgSlug/projects/$slug/sprints/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/welcome'
    | '/login'
    | '/profile'
    | '/'
    | '/oauth/consent'
    | '/orgs/$orgSlug'
    | '/orgs/$orgSlug/projects'
    | '/orgs/$orgSlug/projects/$slug/about'
    | '/orgs/$orgSlug/projects/$slug'
    | '/orgs/$orgSlug/projects/$slug/settings/general'
    | '/orgs/$orgSlug/projects/$slug/settings/integrations'
    | '/orgs/$orgSlug/projects/$slug/settings/statuses'
    | '/orgs/$orgSlug/projects/$slug/settings/team'
    | '/orgs/$orgSlug/projects/$slug/settings/workflow'
    | '/orgs/$orgSlug/projects/$slug/sprints/$groupId'
    | '/orgs/$orgSlug/projects/$slug/tickets/$id'
    | '/orgs/$orgSlug/projects/$slug/settings'
    | '/orgs/$orgSlug/projects/$slug/sprints'
  id:
    | '__root__'
    | '/_authed'
    | '/welcome'
    | '/(public)/login'
    | '/_authed/profile'
    | '/_authed/'
    | '/_authed/orgs/$orgSlug'
    | '/(public)/oauth/consent'
    | '/_authed/orgs/$orgSlug/'
    | '/_authed/orgs/$orgSlug/projects/$slug'
    | '/_authed/orgs/$orgSlug/projects/'
    | '/_authed/orgs/$orgSlug/projects/$slug/settings'
    | '/_authed/orgs/$orgSlug/projects/$slug/sprints'
    | '/_authed/orgs/$orgSlug/projects/$slug/about'
    | '/_authed/orgs/$orgSlug/projects/$slug/'
    | '/_authed/orgs/$orgSlug/projects/$slug/settings/general'
    | '/_authed/orgs/$orgSlug/projects/$slug/settings/integrations'
    | '/_authed/orgs/$orgSlug/projects/$slug/settings/statuses'
    | '/_authed/orgs/$orgSlug/projects/$slug/settings/team'
    | '/_authed/orgs/$orgSlug/projects/$slug/settings/workflow'
    | '/_authed/orgs/$orgSlug/projects/$slug/sprints/$groupId'
    | '/_authed/orgs/$orgSlug/projects/$slug/tickets/$id'
    | '/_authed/orgs/$orgSlug/projects/$slug/settings/'
    | '/_authed/orgs/$orgSlug/projects/$slug/sprints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  publicLoginRoute: typeof publicLoginRoute
  publicOauthConsentRoute: typeof publicOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/oauth/consent': {
      id: '/(public)/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof publicOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/orgs/$orgSlug': {
      id: '/_authed/orgs/$orgSlug'
      path: '/orgs/$orgSlug'
      fullPath: '/orgs/$orgSlug'
      preLoaderRoute: typeof AuthedOrgsOrgSlugRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orgs/$orgSlug/': {
      id: '/_authed/orgs/$orgSlug/'
      path: '/'
      fullPath: '/orgs/$orgSlug/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/': {
      id: '/_authed/orgs/$orgSlug/projects/'
      path: '/projects'
      fullPath: '/orgs/$orgSlug/projects/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug': {
      id: '/_authed/orgs/$orgSlug/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/orgs/$orgSlug/projects/$slug'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/'
      path: '/'
      fullPath: '/orgs/$orgSlug/projects/$slug/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/about': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/about'
      path: '/about'
      fullPath: '/orgs/$orgSlug/projects/$slug/about'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugAboutRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/sprints': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/sprints'
      path: '/sprints'
      fullPath: '/orgs/$orgSlug/projects/$slug/sprints'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/settings': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/settings'
      path: '/settings'
      fullPath: '/orgs/$orgSlug/projects/$slug/settings'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/sprints/': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/sprints/'
      path: '/'
      fullPath: '/orgs/$orgSlug/projects/$slug/sprints/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSprintsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugSprintsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/settings/': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/settings/'
      path: '/'
      fullPath: '/orgs/$orgSlug/projects/$slug/settings/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/tickets/$id': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/orgs/$orgSlug/projects/$slug/tickets/$id'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugTicketsIdRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/sprints/$groupId': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/sprints/$groupId'
      path: '/$groupId'
      fullPath: '/orgs/$orgSlug/projects/$slug/sprints/$groupId'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugSprintsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/settings/workflow': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/settings/workflow'
      path: '/workflow'
      fullPath: '/orgs/$orgSlug/projects/$slug/settings/workflow'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/settings/statuses': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/settings/statuses'
      path: '/statuses'
      fullPath: '/orgs/$orgSlug/projects/$slug/settings/statuses'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsStatusesRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/settings/team': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/settings/team'
      path: '/team'
      fullPath: '/orgs/$orgSlug/projects/$slug/settings/team'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsTeamRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/settings/integrations': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/settings/integrations'
      path: '/integrations'
      fullPath: '/orgs/$orgSlug/projects/$slug/settings/integrations'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/settings/general': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/settings/general'
      path: '/general'
      fullPath: '/orgs/$orgSlug/projects/$slug/settings/general'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute
    }
  }
}

interface AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteChildren {
  AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRoute
  AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRoute
  AuthedOrgsOrgSlugProjectsSlugSettingsStatusesRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsStatusesRoute
  AuthedOrgsOrgSlugProjectsSlugSettingsTeamRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsTeamRoute
  AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRoute
  AuthedOrgsOrgSlugProjectsSlugSettingsIndexRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsIndexRoute
}

const AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteChildren: AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteChildren =
  {
    AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRoute:
      AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRoute,
    AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRoute:
      AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRoute,
    AuthedOrgsOrgSlugProjectsSlugSettingsStatusesRoute:
      AuthedOrgsOrgSlugProjectsSlugSettingsStatusesRoute,
    AuthedOrgsOrgSlugProjectsSlugSettingsTeamRoute:
      AuthedOrgsOrgSlugProjectsSlugSettingsTeamRoute,
    AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRoute:
      AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRoute,
    AuthedOrgsOrgSlugProjectsSlugSettingsIndexRoute:
      AuthedOrgsOrgSlugProjectsSlugSettingsIndexRoute,
  }

const AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteWithChildren =
  AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute._addFileChildren(
    AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteChildren,
  )

interface AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteChildren {
  AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRoute: typeof AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRoute
  AuthedOrgsOrgSlugProjectsSlugSprintsIndexRoute: typeof AuthedOrgsOrgSlugProjectsSlugSprintsIndexRoute
}

const AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteChildren: AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteChildren =
  {
    AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRoute:
      AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRoute,
    AuthedOrgsOrgSlugProjectsSlugSprintsIndexRoute:
      AuthedOrgsOrgSlugProjectsSlugSprintsIndexRoute,
  }

const AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteWithChildren =
  AuthedOrgsOrgSlugProjectsSlugSprintsRouteRoute._addFileChildren(
    AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteChildren,
  )

interface AuthedOrgsOrgSlugProjectsSlugRouteRouteChildren {
  AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteWithChildren
  AuthedOrgsOrgSlugProjectsSlugSprintsRouteRoute: typeof AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteWithChildren
  AuthedOrgsOrgSlugProjectsSlugAboutRoute: typeof AuthedOrgsOrgSlugProjectsSlugAboutRoute
  AuthedOrgsOrgSlugProjectsSlugIndexRoute: typeof AuthedOrgsOrgSlugProjectsSlugIndexRoute
  AuthedOrgsOrgSlugProjectsSlugTicketsIdRoute: typeof AuthedOrgsOrgSlugProjectsSlugTicketsIdRoute
}

const AuthedOrgsOrgSlugProjectsSlugRouteRouteChildren: AuthedOrgsOrgSlugProjectsSlugRouteRouteChildren =
  {
    AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute:
      AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteWithChildren,
    AuthedOrgsOrgSlugProjectsSlugSprintsRouteRoute:
      AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteWithChildren,
    AuthedOrgsOrgSlugProjectsSlugAboutRoute:
      AuthedOrgsOrgSlugProjectsSlugAboutRoute,
    AuthedOrgsOrgSlugProjectsSlugIndexRoute:
      AuthedOrgsOrgSlugProjectsSlugIndexRoute,
    AuthedOrgsOrgSlugProjectsSlugTicketsIdRoute:
      AuthedOrgsOrgSlugProjectsSlugTicketsIdRoute,
  }

const AuthedOrgsOrgSlugProjectsSlugRouteRouteWithChildren =
  AuthedOrgsOrgSlugProjectsSlugRouteRoute._addFileChildren(
    AuthedOrgsOrgSlugProjectsSlugRouteRouteChildren,
  )

interface AuthedOrgsOrgSlugRouteRouteChildren {
  AuthedOrgsOrgSlugIndexRoute: typeof AuthedOrgsOrgSlugIndexRoute
  AuthedOrgsOrgSlugProjectsSlugRouteRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRouteWithChildren
  AuthedOrgsOrgSlugProjectsIndexRoute: typeof AuthedOrgsOrgSlugProjectsIndexRoute
}

const AuthedOrgsOrgSlugRouteRouteChildren: AuthedOrgsOrgSlugRouteRouteChildren =
  {
    AuthedOrgsOrgSlugIndexRoute: AuthedOrgsOrgSlugIndexRoute,
    AuthedOrgsOrgSlugProjectsSlugRouteRoute:
      AuthedOrgsOrgSlugProjectsSlugRouteRouteWithChildren,
    AuthedOrgsOrgSlugProjectsIndexRoute: AuthedOrgsOrgSlugProjectsIndexRoute,
  }

const AuthedOrgsOrgSlugRouteRouteWithChildren =
  AuthedOrgsOrgSlugRouteRoute._addFileChildren(
    AuthedOrgsOrgSlugRouteRouteChildren,
  )

interface AuthedRouteRouteChildren {
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedOrgsOrgSlugRouteRoute: typeof AuthedOrgsOrgSlugRouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedOrgsOrgSlugRouteRoute: AuthedOrgsOrgSlugRouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  publicLoginRoute: publicLoginRoute,
  publicOauthConsentRoute: publicOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
