/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicSpikeRouteRouteImport } from './routes/(public)/spike/route'
import { Route as publicSpikeIndexRouteImport } from './routes/(public)/spike/index'
import { Route as publicSpikePragmaticRouteImport } from './routes/(public)/spike/pragmatic'
import { Route as AuthedOrgsOrgSlugRouteRouteImport } from './routes/_authed/orgs/$orgSlug/route'
import { Route as AuthedOrgsOrgSlugIndexRouteImport } from './routes/_authed/orgs/$orgSlug/index'
import { Route as AuthedOrgsOrgSlugProjectsIndexRouteImport } from './routes/_authed/orgs/$orgSlug/projects/index'
import { Route as AuthedOrgsOrgSlugProjectsSlugRouteRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/route'
import { Route as AuthedOrgsOrgSlugProjectsSlugIndexRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/index'
import { Route as AuthedOrgsOrgSlugProjectsSlugMembersRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/members'
import { Route as AuthedOrgsOrgSlugProjectsSlugAboutRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/about'
import { Route as AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/sprints/route'
import { Route as AuthedOrgsOrgSlugProjectsSlugSprintsIndexRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/sprints/index'
import { Route as AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/sprints/$groupId'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSpikeRouteRoute = publicSpikeRouteRouteImport.update({
  id: '/(public)/spike',
  path: '/spike',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSpikeIndexRoute = publicSpikeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicSpikeRouteRoute,
} as any)
const publicSpikePragmaticRoute = publicSpikePragmaticRouteImport.update({
  id: '/pragmatic',
  path: '/pragmatic',
  getParentRoute: () => publicSpikeRouteRoute,
} as any)
const AuthedOrgsOrgSlugRouteRoute = AuthedOrgsOrgSlugRouteRouteImport.update({
  id: '/orgs/$orgSlug',
  path: '/orgs/$orgSlug',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrgsOrgSlugIndexRoute = AuthedOrgsOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOrgsOrgSlugRouteRoute,
} as any)
const AuthedOrgsOrgSlugProjectsIndexRoute =
  AuthedOrgsOrgSlugProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthedOrgsOrgSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugRouteRoute =
  AuthedOrgsOrgSlugProjectsSlugRouteRouteImport.update({
    id: '/projects/$slug',
    path: '/projects/$slug',
    getParentRoute: () => AuthedOrgsOrgSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugIndexRoute =
  AuthedOrgsOrgSlugProjectsSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugMembersRoute =
  AuthedOrgsOrgSlugProjectsSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugAboutRoute =
  AuthedOrgsOrgSlugProjectsSlugAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSprintsRouteRoute =
  AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteImport.update({
    id: '/sprints',
    path: '/sprints',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSprintsIndexRoute =
  AuthedOrgsOrgSlugProjectsSlugSprintsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugSprintsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRoute =
  AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugSprintsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/spike': typeof publicSpikeRouteRouteWithChildren
  '/login': typeof publicLoginRoute
  '/profile': typeof AuthedProfileRoute
  '/orgs/$orgSlug': typeof AuthedOrgsOrgSlugRouteRouteWithChildren
  '/spike/pragmatic': typeof publicSpikePragmaticRoute
  '/spike/': typeof publicSpikeIndexRoute
  '/orgs/$orgSlug/': typeof AuthedOrgsOrgSlugIndexRoute
  '/orgs/$orgSlug/projects/$slug': typeof AuthedOrgsOrgSlugProjectsSlugRouteRouteWithChildren
  '/orgs/$orgSlug/projects/': typeof AuthedOrgsOrgSlugProjectsIndexRoute
  '/orgs/$orgSlug/projects/$slug/sprints': typeof AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteWithChildren
  '/orgs/$orgSlug/projects/$slug/about': typeof AuthedOrgsOrgSlugProjectsSlugAboutRoute
  '/orgs/$orgSlug/projects/$slug/members': typeof AuthedOrgsOrgSlugProjectsSlugMembersRoute
  '/orgs/$orgSlug/projects/$slug/': typeof AuthedOrgsOrgSlugProjectsSlugIndexRoute
  '/orgs/$orgSlug/projects/$slug/sprints/$groupId': typeof AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRoute
  '/orgs/$orgSlug/projects/$slug/sprints/': typeof AuthedOrgsOrgSlugProjectsSlugSprintsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof publicLoginRoute
  '/profile': typeof AuthedProfileRoute
  '/': typeof AuthedIndexRoute
  '/spike/pragmatic': typeof publicSpikePragmaticRoute
  '/spike': typeof publicSpikeIndexRoute
  '/orgs/$orgSlug': typeof AuthedOrgsOrgSlugIndexRoute
  '/orgs/$orgSlug/projects': typeof AuthedOrgsOrgSlugProjectsIndexRoute
  '/orgs/$orgSlug/projects/$slug/about': typeof AuthedOrgsOrgSlugProjectsSlugAboutRoute
  '/orgs/$orgSlug/projects/$slug/members': typeof AuthedOrgsOrgSlugProjectsSlugMembersRoute
  '/orgs/$orgSlug/projects/$slug': typeof AuthedOrgsOrgSlugProjectsSlugIndexRoute
  '/orgs/$orgSlug/projects/$slug/sprints/$groupId': typeof AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRoute
  '/orgs/$orgSlug/projects/$slug/sprints': typeof AuthedOrgsOrgSlugProjectsSlugSprintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/(public)/spike': typeof publicSpikeRouteRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/orgs/$orgSlug': typeof AuthedOrgsOrgSlugRouteRouteWithChildren
  '/(public)/spike/pragmatic': typeof publicSpikePragmaticRoute
  '/(public)/spike/': typeof publicSpikeIndexRoute
  '/_authed/orgs/$orgSlug/': typeof AuthedOrgsOrgSlugIndexRoute
  '/_authed/orgs/$orgSlug/projects/$slug': typeof AuthedOrgsOrgSlugProjectsSlugRouteRouteWithChildren
  '/_authed/orgs/$orgSlug/projects/': typeof AuthedOrgsOrgSlugProjectsIndexRoute
  '/_authed/orgs/$orgSlug/projects/$slug/sprints': typeof AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteWithChildren
  '/_authed/orgs/$orgSlug/projects/$slug/about': typeof AuthedOrgsOrgSlugProjectsSlugAboutRoute
  '/_authed/orgs/$orgSlug/projects/$slug/members': typeof AuthedOrgsOrgSlugProjectsSlugMembersRoute
  '/_authed/orgs/$orgSlug/projects/$slug/': typeof AuthedOrgsOrgSlugProjectsSlugIndexRoute
  '/_authed/orgs/$orgSlug/projects/$slug/sprints/$groupId': typeof AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRoute
  '/_authed/orgs/$orgSlug/projects/$slug/sprints/': typeof AuthedOrgsOrgSlugProjectsSlugSprintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/spike'
    | '/login'
    | '/profile'
    | '/orgs/$orgSlug'
    | '/spike/pragmatic'
    | '/spike/'
    | '/orgs/$orgSlug/'
    | '/orgs/$orgSlug/projects/$slug'
    | '/orgs/$orgSlug/projects/'
    | '/orgs/$orgSlug/projects/$slug/sprints'
    | '/orgs/$orgSlug/projects/$slug/about'
    | '/orgs/$orgSlug/projects/$slug/members'
    | '/orgs/$orgSlug/projects/$slug/'
    | '/orgs/$orgSlug/projects/$slug/sprints/$groupId'
    | '/orgs/$orgSlug/projects/$slug/sprints/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/profile'
    | '/'
    | '/spike/pragmatic'
    | '/spike'
    | '/orgs/$orgSlug'
    | '/orgs/$orgSlug/projects'
    | '/orgs/$orgSlug/projects/$slug/about'
    | '/orgs/$orgSlug/projects/$slug/members'
    | '/orgs/$orgSlug/projects/$slug'
    | '/orgs/$orgSlug/projects/$slug/sprints/$groupId'
    | '/orgs/$orgSlug/projects/$slug/sprints'
  id:
    | '__root__'
    | '/_authed'
    | '/(public)/spike'
    | '/(public)/login'
    | '/_authed/profile'
    | '/_authed/'
    | '/_authed/orgs/$orgSlug'
    | '/(public)/spike/pragmatic'
    | '/(public)/spike/'
    | '/_authed/orgs/$orgSlug/'
    | '/_authed/orgs/$orgSlug/projects/$slug'
    | '/_authed/orgs/$orgSlug/projects/'
    | '/_authed/orgs/$orgSlug/projects/$slug/sprints'
    | '/_authed/orgs/$orgSlug/projects/$slug/about'
    | '/_authed/orgs/$orgSlug/projects/$slug/members'
    | '/_authed/orgs/$orgSlug/projects/$slug/'
    | '/_authed/orgs/$orgSlug/projects/$slug/sprints/$groupId'
    | '/_authed/orgs/$orgSlug/projects/$slug/sprints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  publicSpikeRouteRoute: typeof publicSpikeRouteRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/spike': {
      id: '/(public)/spike'
      path: '/spike'
      fullPath: '/spike'
      preLoaderRoute: typeof publicSpikeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/spike/': {
      id: '/(public)/spike/'
      path: '/'
      fullPath: '/spike/'
      preLoaderRoute: typeof publicSpikeIndexRouteImport
      parentRoute: typeof publicSpikeRouteRoute
    }
    '/(public)/spike/pragmatic': {
      id: '/(public)/spike/pragmatic'
      path: '/pragmatic'
      fullPath: '/spike/pragmatic'
      preLoaderRoute: typeof publicSpikePragmaticRouteImport
      parentRoute: typeof publicSpikeRouteRoute
    }
    '/_authed/orgs/$orgSlug': {
      id: '/_authed/orgs/$orgSlug'
      path: '/orgs/$orgSlug'
      fullPath: '/orgs/$orgSlug'
      preLoaderRoute: typeof AuthedOrgsOrgSlugRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orgs/$orgSlug/': {
      id: '/_authed/orgs/$orgSlug/'
      path: '/'
      fullPath: '/orgs/$orgSlug/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/': {
      id: '/_authed/orgs/$orgSlug/projects/'
      path: '/projects'
      fullPath: '/orgs/$orgSlug/projects/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug': {
      id: '/_authed/orgs/$orgSlug/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/orgs/$orgSlug/projects/$slug'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/'
      path: '/'
      fullPath: '/orgs/$orgSlug/projects/$slug/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/members': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/members'
      path: '/members'
      fullPath: '/orgs/$orgSlug/projects/$slug/members'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugMembersRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/about': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/about'
      path: '/about'
      fullPath: '/orgs/$orgSlug/projects/$slug/about'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugAboutRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/sprints': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/sprints'
      path: '/sprints'
      fullPath: '/orgs/$orgSlug/projects/$slug/sprints'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/sprints/': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/sprints/'
      path: '/'
      fullPath: '/orgs/$orgSlug/projects/$slug/sprints/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSprintsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugSprintsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/sprints/$groupId': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/sprints/$groupId'
      path: '/$groupId'
      fullPath: '/orgs/$orgSlug/projects/$slug/sprints/$groupId'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugSprintsRouteRoute
    }
  }
}

interface AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteChildren {
  AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRoute: typeof AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRoute
  AuthedOrgsOrgSlugProjectsSlugSprintsIndexRoute: typeof AuthedOrgsOrgSlugProjectsSlugSprintsIndexRoute
}

const AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteChildren: AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteChildren =
  {
    AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRoute:
      AuthedOrgsOrgSlugProjectsSlugSprintsGroupIdRoute,
    AuthedOrgsOrgSlugProjectsSlugSprintsIndexRoute:
      AuthedOrgsOrgSlugProjectsSlugSprintsIndexRoute,
  }

const AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteWithChildren =
  AuthedOrgsOrgSlugProjectsSlugSprintsRouteRoute._addFileChildren(
    AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteChildren,
  )

interface AuthedOrgsOrgSlugProjectsSlugRouteRouteChildren {
  AuthedOrgsOrgSlugProjectsSlugSprintsRouteRoute: typeof AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteWithChildren
  AuthedOrgsOrgSlugProjectsSlugAboutRoute: typeof AuthedOrgsOrgSlugProjectsSlugAboutRoute
  AuthedOrgsOrgSlugProjectsSlugMembersRoute: typeof AuthedOrgsOrgSlugProjectsSlugMembersRoute
  AuthedOrgsOrgSlugProjectsSlugIndexRoute: typeof AuthedOrgsOrgSlugProjectsSlugIndexRoute
}

const AuthedOrgsOrgSlugProjectsSlugRouteRouteChildren: AuthedOrgsOrgSlugProjectsSlugRouteRouteChildren =
  {
    AuthedOrgsOrgSlugProjectsSlugSprintsRouteRoute:
      AuthedOrgsOrgSlugProjectsSlugSprintsRouteRouteWithChildren,
    AuthedOrgsOrgSlugProjectsSlugAboutRoute:
      AuthedOrgsOrgSlugProjectsSlugAboutRoute,
    AuthedOrgsOrgSlugProjectsSlugMembersRoute:
      AuthedOrgsOrgSlugProjectsSlugMembersRoute,
    AuthedOrgsOrgSlugProjectsSlugIndexRoute:
      AuthedOrgsOrgSlugProjectsSlugIndexRoute,
  }

const AuthedOrgsOrgSlugProjectsSlugRouteRouteWithChildren =
  AuthedOrgsOrgSlugProjectsSlugRouteRoute._addFileChildren(
    AuthedOrgsOrgSlugProjectsSlugRouteRouteChildren,
  )

interface AuthedOrgsOrgSlugRouteRouteChildren {
  AuthedOrgsOrgSlugIndexRoute: typeof AuthedOrgsOrgSlugIndexRoute
  AuthedOrgsOrgSlugProjectsSlugRouteRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRouteWithChildren
  AuthedOrgsOrgSlugProjectsIndexRoute: typeof AuthedOrgsOrgSlugProjectsIndexRoute
}

const AuthedOrgsOrgSlugRouteRouteChildren: AuthedOrgsOrgSlugRouteRouteChildren =
  {
    AuthedOrgsOrgSlugIndexRoute: AuthedOrgsOrgSlugIndexRoute,
    AuthedOrgsOrgSlugProjectsSlugRouteRoute:
      AuthedOrgsOrgSlugProjectsSlugRouteRouteWithChildren,
    AuthedOrgsOrgSlugProjectsIndexRoute: AuthedOrgsOrgSlugProjectsIndexRoute,
  }

const AuthedOrgsOrgSlugRouteRouteWithChildren =
  AuthedOrgsOrgSlugRouteRoute._addFileChildren(
    AuthedOrgsOrgSlugRouteRouteChildren,
  )

interface AuthedRouteRouteChildren {
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedOrgsOrgSlugRouteRoute: typeof AuthedOrgsOrgSlugRouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedOrgsOrgSlugRouteRoute: AuthedOrgsOrgSlugRouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface publicSpikeRouteRouteChildren {
  publicSpikePragmaticRoute: typeof publicSpikePragmaticRoute
  publicSpikeIndexRoute: typeof publicSpikeIndexRoute
}

const publicSpikeRouteRouteChildren: publicSpikeRouteRouteChildren = {
  publicSpikePragmaticRoute: publicSpikePragmaticRoute,
  publicSpikeIndexRoute: publicSpikeIndexRoute,
}

const publicSpikeRouteRouteWithChildren =
  publicSpikeRouteRoute._addFileChildren(publicSpikeRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  publicSpikeRouteRoute: publicSpikeRouteRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
