// apps/frontend/src/main.tsx
//
// React entry point. Pure plumbing: mount React, hand control to TanStack
// Router. There is no ProjectProject-specific logic here — every page lives in
// `src/routes/`, and `routeTree.gen.ts` is auto-generated by the router
// plugin during `vite dev`.
//
// You should not need to touch this file in Chapter 0.

import { RegistryContext } from "@effect/atom-react"
import {
  createBrowserHistory,
  createRouter,
  RouterProvider
} from "@tanstack/react-router"
import { StrictMode, useSyncExternalStore } from "react"
import ReactDOM from "react-dom/client"

import { createSessionCache } from "./lib/sessionCache"
import { routeTree } from "./routeTree.gen"
import { authClient } from "./services/AuthClient"

import "./styles.css"

const history = createBrowserHistory()
const sessions = createSessionCache((registry) =>
  createRouter({
    routeTree,
    history,
    defaultPreload: "intent",
    scrollRestoration: true,
    scrollToTopSelectors: ["[data-scroll-root]"],
    context: { registry }
  })
)

authClient.$store.atoms.$sessionSignal.listen(sessions.refreshIdentity)
window.addEventListener("focus", sessions.refreshIdentity)

function App() {
  const session = useSyncExternalStore(sessions.subscribe, sessions.getSnapshot)
  if (!session.ready) return null
  return (
    <RegistryContext.Provider key={session.generation} value={session.registry}>
      <RouterProvider router={session.router} />
    </RegistryContext.Provider>
  )
}

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof sessions.getSnapshot>["router"]
  }
}

const rootEl = document.getElementById("root")
if (!rootEl) throw new Error("Root element #root not found")

ReactDOM.createRoot(rootEl).render(
  <StrictMode>
    <App />
  </StrictMode>
)
