/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as InviteInvitationIdRouteImport } from './routes/invite.$invitationId'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicOauthConsentRouteImport } from './routes/(public)/oauth.consent'
import { Route as AuthedOrgsOrgSlugRouteRouteImport } from './routes/_authed/orgs/$orgSlug/route'
import { Route as AuthedOrgsOrgSlugIndexRouteImport } from './routes/_authed/orgs/$orgSlug/index'
import { Route as AuthedOrgsOrgSlugSettingsRouteRouteImport } from './routes/_authed/orgs/$orgSlug/settings/route'
import { Route as AuthedOrgsOrgSlugSettingsIndexRouteImport } from './routes/_authed/orgs/$orgSlug/settings/index'
import { Route as AuthedOrgsOrgSlugProjectsIndexRouteImport } from './routes/_authed/orgs/$orgSlug/projects/index'
import { Route as AuthedOrgsOrgSlugSettingsStorageRouteImport } from './routes/_authed/orgs/$orgSlug/settings/storage'
import { Route as AuthedOrgsOrgSlugSettingsMembersRouteImport } from './routes/_authed/orgs/$orgSlug/settings/members'
import { Route as AuthedOrgsOrgSlugSettingsGeneralRouteImport } from './routes/_authed/orgs/$orgSlug/settings/general'
import { Route as AuthedOrgsOrgSlugSettingsDangerRouteImport } from './routes/_authed/orgs/$orgSlug/settings/danger'
import { Route as AuthedOrgsOrgSlugSettingsAttachmentsRouteImport } from './routes/_authed/orgs/$orgSlug/settings/attachments'
import { Route as AuthedOrgsOrgSlugProjectsSlugRouteRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/route'
import { Route as AuthedOrgsOrgSlugSettingsTemplatesIndexRouteImport } from './routes/_authed/orgs/$orgSlug/settings/templates/index'
import { Route as AuthedOrgsOrgSlugSettingsTemplatesTemplateKeyRouteImport } from './routes/_authed/orgs/$orgSlug/settings/templates/$templateKey'
import { Route as AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/settings/route'
import { Route as AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/route'
import { Route as AuthedOrgsOrgSlugProjectsSlugSettingsIndexRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/settings/index'
import { Route as AuthedOrgsOrgSlugProjectsSlugProjectHeaderIndexRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/index'
import { Route as AuthedOrgsOrgSlugSettingsTemplatesBlocksBlockKeyRouteImport } from './routes/_authed/orgs/$orgSlug/settings/templates/blocks.$blockKey'
import { Route as AuthedOrgsOrgSlugProjectsSlugTicketsIdRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/tickets/$id'
import { Route as AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/settings/workflow'
import { Route as AuthedOrgsOrgSlugProjectsSlugSettingsTeamRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/settings/team'
import { Route as AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/settings/integrations'
import { Route as AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/settings/general'
import { Route as AuthedOrgsOrgSlugProjectsSlugProjectHeaderAboutRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/about'
import { Route as AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/sprints/route'
import { Route as AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesIndexRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/settings/templates/index'
import { Route as AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsIndexRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/sprints/index'
import { Route as AuthedOrgsOrgSlugProjectsSlugTicketsIdSplitRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/tickets/$id_.split'
import { Route as AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesTemplateKeyRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/settings/templates/$templateKey'
import { Route as AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsGroupIdRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/sprints/$groupId'
import { Route as AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesBlocksBlockKeyRouteImport } from './routes/_authed/orgs/$orgSlug/projects/$slug/settings/templates/blocks.$blockKey'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const publicOauthConsentRoute = publicOauthConsentRouteImport.update({
  id: '/(public)/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOrgsOrgSlugRouteRoute = AuthedOrgsOrgSlugRouteRouteImport.update({
  id: '/orgs/$orgSlug',
  path: '/orgs/$orgSlug',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrgsOrgSlugIndexRoute = AuthedOrgsOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOrgsOrgSlugRouteRoute,
} as any)
const AuthedOrgsOrgSlugSettingsRouteRoute =
  AuthedOrgsOrgSlugSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedOrgsOrgSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugSettingsIndexRoute =
  AuthedOrgsOrgSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgsOrgSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsIndexRoute =
  AuthedOrgsOrgSlugProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthedOrgsOrgSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugSettingsStorageRoute =
  AuthedOrgsOrgSlugSettingsStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => AuthedOrgsOrgSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugSettingsMembersRoute =
  AuthedOrgsOrgSlugSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthedOrgsOrgSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugSettingsGeneralRoute =
  AuthedOrgsOrgSlugSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthedOrgsOrgSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugSettingsDangerRoute =
  AuthedOrgsOrgSlugSettingsDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => AuthedOrgsOrgSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugSettingsAttachmentsRoute =
  AuthedOrgsOrgSlugSettingsAttachmentsRouteImport.update({
    id: '/attachments',
    path: '/attachments',
    getParentRoute: () => AuthedOrgsOrgSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugRouteRoute =
  AuthedOrgsOrgSlugProjectsSlugRouteRouteImport.update({
    id: '/projects/$slug',
    path: '/projects/$slug',
    getParentRoute: () => AuthedOrgsOrgSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugSettingsTemplatesIndexRoute =
  AuthedOrgsOrgSlugSettingsTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthedOrgsOrgSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugSettingsTemplatesTemplateKeyRoute =
  AuthedOrgsOrgSlugSettingsTemplatesTemplateKeyRouteImport.update({
    id: '/templates/$templateKey',
    path: '/templates/$templateKey',
    getParentRoute: () => AuthedOrgsOrgSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute =
  AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRoute =
  AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRouteImport.update({
    id: '/_projectHeader',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSettingsIndexRoute =
  AuthedOrgsOrgSlugProjectsSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugProjectHeaderIndexRoute =
  AuthedOrgsOrgSlugProjectsSlugProjectHeaderIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRoute,
  } as any)
const AuthedOrgsOrgSlugSettingsTemplatesBlocksBlockKeyRoute =
  AuthedOrgsOrgSlugSettingsTemplatesBlocksBlockKeyRouteImport.update({
    id: '/templates/blocks/$blockKey',
    path: '/templates/blocks/$blockKey',
    getParentRoute: () => AuthedOrgsOrgSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugTicketsIdRoute =
  AuthedOrgsOrgSlugProjectsSlugTicketsIdRouteImport.update({
    id: '/tickets/$id',
    path: '/tickets/$id',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRoute =
  AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRouteImport.update({
    id: '/workflow',
    path: '/workflow',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSettingsTeamRoute =
  AuthedOrgsOrgSlugProjectsSlugSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRoute =
  AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRoute =
  AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugProjectHeaderAboutRoute =
  AuthedOrgsOrgSlugProjectsSlugProjectHeaderAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRoute =
  AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRouteImport.update({
    id: '/sprints',
    path: '/sprints',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesIndexRoute =
  AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsIndexRoute =
  AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugTicketsIdSplitRoute =
  AuthedOrgsOrgSlugProjectsSlugTicketsIdSplitRouteImport.update({
    id: '/tickets/$id_/split',
    path: '/tickets/$id/split',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesTemplateKeyRoute =
  AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesTemplateKeyRouteImport.update({
    id: '/templates/$templateKey',
    path: '/templates/$templateKey',
    getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsGroupIdRoute =
  AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () =>
      AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRoute,
  } as any)
const AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesBlocksBlockKeyRoute =
  AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesBlocksBlockKeyRouteImport.update(
    {
      id: '/templates/blocks/$blockKey',
      path: '/templates/blocks/$blockKey',
      getParentRoute: () => AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/welcome': typeof WelcomeRoute
  '/login': typeof publicLoginRoute
  '/profile': typeof AuthedProfileRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/orgs/$orgSlug': typeof AuthedOrgsOrgSlugRouteRouteWithChildren
  '/oauth/consent': typeof publicOauthConsentRoute
  '/orgs/$orgSlug/settings': typeof AuthedOrgsOrgSlugSettingsRouteRouteWithChildren
  '/orgs/$orgSlug/': typeof AuthedOrgsOrgSlugIndexRoute
  '/orgs/$orgSlug/projects/$slug': typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRouteWithChildren
  '/orgs/$orgSlug/settings/attachments': typeof AuthedOrgsOrgSlugSettingsAttachmentsRoute
  '/orgs/$orgSlug/settings/danger': typeof AuthedOrgsOrgSlugSettingsDangerRoute
  '/orgs/$orgSlug/settings/general': typeof AuthedOrgsOrgSlugSettingsGeneralRoute
  '/orgs/$orgSlug/settings/members': typeof AuthedOrgsOrgSlugSettingsMembersRoute
  '/orgs/$orgSlug/settings/storage': typeof AuthedOrgsOrgSlugSettingsStorageRoute
  '/orgs/$orgSlug/projects/': typeof AuthedOrgsOrgSlugProjectsIndexRoute
  '/orgs/$orgSlug/settings/': typeof AuthedOrgsOrgSlugSettingsIndexRoute
  '/orgs/$orgSlug/projects/$slug/settings': typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteWithChildren
  '/orgs/$orgSlug/settings/templates/$templateKey': typeof AuthedOrgsOrgSlugSettingsTemplatesTemplateKeyRoute
  '/orgs/$orgSlug/settings/templates/': typeof AuthedOrgsOrgSlugSettingsTemplatesIndexRoute
  '/orgs/$orgSlug/projects/$slug/sprints': typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRouteWithChildren
  '/orgs/$orgSlug/projects/$slug/about': typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderAboutRoute
  '/orgs/$orgSlug/projects/$slug/settings/general': typeof AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRoute
  '/orgs/$orgSlug/projects/$slug/settings/integrations': typeof AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRoute
  '/orgs/$orgSlug/projects/$slug/settings/team': typeof AuthedOrgsOrgSlugProjectsSlugSettingsTeamRoute
  '/orgs/$orgSlug/projects/$slug/settings/workflow': typeof AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRoute
  '/orgs/$orgSlug/projects/$slug/tickets/$id': typeof AuthedOrgsOrgSlugProjectsSlugTicketsIdRoute
  '/orgs/$orgSlug/settings/templates/blocks/$blockKey': typeof AuthedOrgsOrgSlugSettingsTemplatesBlocksBlockKeyRoute
  '/orgs/$orgSlug/projects/$slug/': typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderIndexRoute
  '/orgs/$orgSlug/projects/$slug/settings/': typeof AuthedOrgsOrgSlugProjectsSlugSettingsIndexRoute
  '/orgs/$orgSlug/projects/$slug/sprints/$groupId': typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsGroupIdRoute
  '/orgs/$orgSlug/projects/$slug/settings/templates/$templateKey': typeof AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesTemplateKeyRoute
  '/orgs/$orgSlug/projects/$slug/tickets/$id/split': typeof AuthedOrgsOrgSlugProjectsSlugTicketsIdSplitRoute
  '/orgs/$orgSlug/projects/$slug/sprints/': typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsIndexRoute
  '/orgs/$orgSlug/projects/$slug/settings/templates/': typeof AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesIndexRoute
  '/orgs/$orgSlug/projects/$slug/settings/templates/blocks/$blockKey': typeof AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesBlocksBlockKeyRoute
}
export interface FileRoutesByTo {
  '/welcome': typeof WelcomeRoute
  '/login': typeof publicLoginRoute
  '/profile': typeof AuthedProfileRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/': typeof AuthedIndexRoute
  '/oauth/consent': typeof publicOauthConsentRoute
  '/orgs/$orgSlug': typeof AuthedOrgsOrgSlugIndexRoute
  '/orgs/$orgSlug/projects/$slug': typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderIndexRoute
  '/orgs/$orgSlug/settings/attachments': typeof AuthedOrgsOrgSlugSettingsAttachmentsRoute
  '/orgs/$orgSlug/settings/danger': typeof AuthedOrgsOrgSlugSettingsDangerRoute
  '/orgs/$orgSlug/settings/general': typeof AuthedOrgsOrgSlugSettingsGeneralRoute
  '/orgs/$orgSlug/settings/members': typeof AuthedOrgsOrgSlugSettingsMembersRoute
  '/orgs/$orgSlug/settings/storage': typeof AuthedOrgsOrgSlugSettingsStorageRoute
  '/orgs/$orgSlug/projects': typeof AuthedOrgsOrgSlugProjectsIndexRoute
  '/orgs/$orgSlug/settings': typeof AuthedOrgsOrgSlugSettingsIndexRoute
  '/orgs/$orgSlug/settings/templates/$templateKey': typeof AuthedOrgsOrgSlugSettingsTemplatesTemplateKeyRoute
  '/orgs/$orgSlug/settings/templates': typeof AuthedOrgsOrgSlugSettingsTemplatesIndexRoute
  '/orgs/$orgSlug/projects/$slug/about': typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderAboutRoute
  '/orgs/$orgSlug/projects/$slug/settings/general': typeof AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRoute
  '/orgs/$orgSlug/projects/$slug/settings/integrations': typeof AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRoute
  '/orgs/$orgSlug/projects/$slug/settings/team': typeof AuthedOrgsOrgSlugProjectsSlugSettingsTeamRoute
  '/orgs/$orgSlug/projects/$slug/settings/workflow': typeof AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRoute
  '/orgs/$orgSlug/projects/$slug/tickets/$id': typeof AuthedOrgsOrgSlugProjectsSlugTicketsIdRoute
  '/orgs/$orgSlug/settings/templates/blocks/$blockKey': typeof AuthedOrgsOrgSlugSettingsTemplatesBlocksBlockKeyRoute
  '/orgs/$orgSlug/projects/$slug/settings': typeof AuthedOrgsOrgSlugProjectsSlugSettingsIndexRoute
  '/orgs/$orgSlug/projects/$slug/sprints/$groupId': typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsGroupIdRoute
  '/orgs/$orgSlug/projects/$slug/settings/templates/$templateKey': typeof AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesTemplateKeyRoute
  '/orgs/$orgSlug/projects/$slug/tickets/$id/split': typeof AuthedOrgsOrgSlugProjectsSlugTicketsIdSplitRoute
  '/orgs/$orgSlug/projects/$slug/sprints': typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsIndexRoute
  '/orgs/$orgSlug/projects/$slug/settings/templates': typeof AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesIndexRoute
  '/orgs/$orgSlug/projects/$slug/settings/templates/blocks/$blockKey': typeof AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesBlocksBlockKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/(public)/login': typeof publicLoginRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/orgs/$orgSlug': typeof AuthedOrgsOrgSlugRouteRouteWithChildren
  '/(public)/oauth/consent': typeof publicOauthConsentRoute
  '/_authed/orgs/$orgSlug/settings': typeof AuthedOrgsOrgSlugSettingsRouteRouteWithChildren
  '/_authed/orgs/$orgSlug/': typeof AuthedOrgsOrgSlugIndexRoute
  '/_authed/orgs/$orgSlug/projects/$slug': typeof AuthedOrgsOrgSlugProjectsSlugRouteRouteWithChildren
  '/_authed/orgs/$orgSlug/settings/attachments': typeof AuthedOrgsOrgSlugSettingsAttachmentsRoute
  '/_authed/orgs/$orgSlug/settings/danger': typeof AuthedOrgsOrgSlugSettingsDangerRoute
  '/_authed/orgs/$orgSlug/settings/general': typeof AuthedOrgsOrgSlugSettingsGeneralRoute
  '/_authed/orgs/$orgSlug/settings/members': typeof AuthedOrgsOrgSlugSettingsMembersRoute
  '/_authed/orgs/$orgSlug/settings/storage': typeof AuthedOrgsOrgSlugSettingsStorageRoute
  '/_authed/orgs/$orgSlug/projects/': typeof AuthedOrgsOrgSlugProjectsIndexRoute
  '/_authed/orgs/$orgSlug/settings/': typeof AuthedOrgsOrgSlugSettingsIndexRoute
  '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader': typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRouteWithChildren
  '/_authed/orgs/$orgSlug/projects/$slug/settings': typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteWithChildren
  '/_authed/orgs/$orgSlug/settings/templates/$templateKey': typeof AuthedOrgsOrgSlugSettingsTemplatesTemplateKeyRoute
  '/_authed/orgs/$orgSlug/settings/templates/': typeof AuthedOrgsOrgSlugSettingsTemplatesIndexRoute
  '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/sprints': typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRouteWithChildren
  '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/about': typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderAboutRoute
  '/_authed/orgs/$orgSlug/projects/$slug/settings/general': typeof AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRoute
  '/_authed/orgs/$orgSlug/projects/$slug/settings/integrations': typeof AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRoute
  '/_authed/orgs/$orgSlug/projects/$slug/settings/team': typeof AuthedOrgsOrgSlugProjectsSlugSettingsTeamRoute
  '/_authed/orgs/$orgSlug/projects/$slug/settings/workflow': typeof AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRoute
  '/_authed/orgs/$orgSlug/projects/$slug/tickets/$id': typeof AuthedOrgsOrgSlugProjectsSlugTicketsIdRoute
  '/_authed/orgs/$orgSlug/settings/templates/blocks/$blockKey': typeof AuthedOrgsOrgSlugSettingsTemplatesBlocksBlockKeyRoute
  '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/': typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderIndexRoute
  '/_authed/orgs/$orgSlug/projects/$slug/settings/': typeof AuthedOrgsOrgSlugProjectsSlugSettingsIndexRoute
  '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/sprints/$groupId': typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsGroupIdRoute
  '/_authed/orgs/$orgSlug/projects/$slug/settings/templates/$templateKey': typeof AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesTemplateKeyRoute
  '/_authed/orgs/$orgSlug/projects/$slug/tickets/$id_/split': typeof AuthedOrgsOrgSlugProjectsSlugTicketsIdSplitRoute
  '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/sprints/': typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsIndexRoute
  '/_authed/orgs/$orgSlug/projects/$slug/settings/templates/': typeof AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesIndexRoute
  '/_authed/orgs/$orgSlug/projects/$slug/settings/templates/blocks/$blockKey': typeof AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesBlocksBlockKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome'
    | '/login'
    | '/profile'
    | '/invite/$invitationId'
    | '/orgs/$orgSlug'
    | '/oauth/consent'
    | '/orgs/$orgSlug/settings'
    | '/orgs/$orgSlug/'
    | '/orgs/$orgSlug/projects/$slug'
    | '/orgs/$orgSlug/settings/attachments'
    | '/orgs/$orgSlug/settings/danger'
    | '/orgs/$orgSlug/settings/general'
    | '/orgs/$orgSlug/settings/members'
    | '/orgs/$orgSlug/settings/storage'
    | '/orgs/$orgSlug/projects/'
    | '/orgs/$orgSlug/settings/'
    | '/orgs/$orgSlug/projects/$slug/settings'
    | '/orgs/$orgSlug/settings/templates/$templateKey'
    | '/orgs/$orgSlug/settings/templates/'
    | '/orgs/$orgSlug/projects/$slug/sprints'
    | '/orgs/$orgSlug/projects/$slug/about'
    | '/orgs/$orgSlug/projects/$slug/settings/general'
    | '/orgs/$orgSlug/projects/$slug/settings/integrations'
    | '/orgs/$orgSlug/projects/$slug/settings/team'
    | '/orgs/$orgSlug/projects/$slug/settings/workflow'
    | '/orgs/$orgSlug/projects/$slug/tickets/$id'
    | '/orgs/$orgSlug/settings/templates/blocks/$blockKey'
    | '/orgs/$orgSlug/projects/$slug/'
    | '/orgs/$orgSlug/projects/$slug/settings/'
    | '/orgs/$orgSlug/projects/$slug/sprints/$groupId'
    | '/orgs/$orgSlug/projects/$slug/settings/templates/$templateKey'
    | '/orgs/$orgSlug/projects/$slug/tickets/$id/split'
    | '/orgs/$orgSlug/projects/$slug/sprints/'
    | '/orgs/$orgSlug/projects/$slug/settings/templates/'
    | '/orgs/$orgSlug/projects/$slug/settings/templates/blocks/$blockKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/welcome'
    | '/login'
    | '/profile'
    | '/invite/$invitationId'
    | '/'
    | '/oauth/consent'
    | '/orgs/$orgSlug'
    | '/orgs/$orgSlug/projects/$slug'
    | '/orgs/$orgSlug/settings/attachments'
    | '/orgs/$orgSlug/settings/danger'
    | '/orgs/$orgSlug/settings/general'
    | '/orgs/$orgSlug/settings/members'
    | '/orgs/$orgSlug/settings/storage'
    | '/orgs/$orgSlug/projects'
    | '/orgs/$orgSlug/settings'
    | '/orgs/$orgSlug/settings/templates/$templateKey'
    | '/orgs/$orgSlug/settings/templates'
    | '/orgs/$orgSlug/projects/$slug/about'
    | '/orgs/$orgSlug/projects/$slug/settings/general'
    | '/orgs/$orgSlug/projects/$slug/settings/integrations'
    | '/orgs/$orgSlug/projects/$slug/settings/team'
    | '/orgs/$orgSlug/projects/$slug/settings/workflow'
    | '/orgs/$orgSlug/projects/$slug/tickets/$id'
    | '/orgs/$orgSlug/settings/templates/blocks/$blockKey'
    | '/orgs/$orgSlug/projects/$slug/settings'
    | '/orgs/$orgSlug/projects/$slug/sprints/$groupId'
    | '/orgs/$orgSlug/projects/$slug/settings/templates/$templateKey'
    | '/orgs/$orgSlug/projects/$slug/tickets/$id/split'
    | '/orgs/$orgSlug/projects/$slug/sprints'
    | '/orgs/$orgSlug/projects/$slug/settings/templates'
    | '/orgs/$orgSlug/projects/$slug/settings/templates/blocks/$blockKey'
  id:
    | '__root__'
    | '/_authed'
    | '/welcome'
    | '/(public)/login'
    | '/_authed/profile'
    | '/invite/$invitationId'
    | '/_authed/'
    | '/_authed/orgs/$orgSlug'
    | '/(public)/oauth/consent'
    | '/_authed/orgs/$orgSlug/settings'
    | '/_authed/orgs/$orgSlug/'
    | '/_authed/orgs/$orgSlug/projects/$slug'
    | '/_authed/orgs/$orgSlug/settings/attachments'
    | '/_authed/orgs/$orgSlug/settings/danger'
    | '/_authed/orgs/$orgSlug/settings/general'
    | '/_authed/orgs/$orgSlug/settings/members'
    | '/_authed/orgs/$orgSlug/settings/storage'
    | '/_authed/orgs/$orgSlug/projects/'
    | '/_authed/orgs/$orgSlug/settings/'
    | '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader'
    | '/_authed/orgs/$orgSlug/projects/$slug/settings'
    | '/_authed/orgs/$orgSlug/settings/templates/$templateKey'
    | '/_authed/orgs/$orgSlug/settings/templates/'
    | '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/sprints'
    | '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/about'
    | '/_authed/orgs/$orgSlug/projects/$slug/settings/general'
    | '/_authed/orgs/$orgSlug/projects/$slug/settings/integrations'
    | '/_authed/orgs/$orgSlug/projects/$slug/settings/team'
    | '/_authed/orgs/$orgSlug/projects/$slug/settings/workflow'
    | '/_authed/orgs/$orgSlug/projects/$slug/tickets/$id'
    | '/_authed/orgs/$orgSlug/settings/templates/blocks/$blockKey'
    | '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/'
    | '/_authed/orgs/$orgSlug/projects/$slug/settings/'
    | '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/sprints/$groupId'
    | '/_authed/orgs/$orgSlug/projects/$slug/settings/templates/$templateKey'
    | '/_authed/orgs/$orgSlug/projects/$slug/tickets/$id_/split'
    | '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/sprints/'
    | '/_authed/orgs/$orgSlug/projects/$slug/settings/templates/'
    | '/_authed/orgs/$orgSlug/projects/$slug/settings/templates/blocks/$blockKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  publicLoginRoute: typeof publicLoginRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
  publicOauthConsentRoute: typeof publicOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/oauth/consent': {
      id: '/(public)/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof publicOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/orgs/$orgSlug': {
      id: '/_authed/orgs/$orgSlug'
      path: '/orgs/$orgSlug'
      fullPath: '/orgs/$orgSlug'
      preLoaderRoute: typeof AuthedOrgsOrgSlugRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/orgs/$orgSlug/': {
      id: '/_authed/orgs/$orgSlug/'
      path: '/'
      fullPath: '/orgs/$orgSlug/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/settings': {
      id: '/_authed/orgs/$orgSlug/settings'
      path: '/settings'
      fullPath: '/orgs/$orgSlug/settings'
      preLoaderRoute: typeof AuthedOrgsOrgSlugSettingsRouteRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/settings/': {
      id: '/_authed/orgs/$orgSlug/settings/'
      path: '/'
      fullPath: '/orgs/$orgSlug/settings/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugSettingsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/': {
      id: '/_authed/orgs/$orgSlug/projects/'
      path: '/projects'
      fullPath: '/orgs/$orgSlug/projects/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/settings/storage': {
      id: '/_authed/orgs/$orgSlug/settings/storage'
      path: '/storage'
      fullPath: '/orgs/$orgSlug/settings/storage'
      preLoaderRoute: typeof AuthedOrgsOrgSlugSettingsStorageRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/settings/members': {
      id: '/_authed/orgs/$orgSlug/settings/members'
      path: '/members'
      fullPath: '/orgs/$orgSlug/settings/members'
      preLoaderRoute: typeof AuthedOrgsOrgSlugSettingsMembersRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/settings/general': {
      id: '/_authed/orgs/$orgSlug/settings/general'
      path: '/general'
      fullPath: '/orgs/$orgSlug/settings/general'
      preLoaderRoute: typeof AuthedOrgsOrgSlugSettingsGeneralRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/settings/danger': {
      id: '/_authed/orgs/$orgSlug/settings/danger'
      path: '/danger'
      fullPath: '/orgs/$orgSlug/settings/danger'
      preLoaderRoute: typeof AuthedOrgsOrgSlugSettingsDangerRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/settings/attachments': {
      id: '/_authed/orgs/$orgSlug/settings/attachments'
      path: '/attachments'
      fullPath: '/orgs/$orgSlug/settings/attachments'
      preLoaderRoute: typeof AuthedOrgsOrgSlugSettingsAttachmentsRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug': {
      id: '/_authed/orgs/$orgSlug/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/orgs/$orgSlug/projects/$slug'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/settings/templates/': {
      id: '/_authed/orgs/$orgSlug/settings/templates/'
      path: '/templates'
      fullPath: '/orgs/$orgSlug/settings/templates/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugSettingsTemplatesIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/settings/templates/$templateKey': {
      id: '/_authed/orgs/$orgSlug/settings/templates/$templateKey'
      path: '/templates/$templateKey'
      fullPath: '/orgs/$orgSlug/settings/templates/$templateKey'
      preLoaderRoute: typeof AuthedOrgsOrgSlugSettingsTemplatesTemplateKeyRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/settings': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/settings'
      path: '/settings'
      fullPath: '/orgs/$orgSlug/projects/$slug/settings'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader'
      path: ''
      fullPath: '/orgs/$orgSlug/projects/$slug'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/settings/': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/settings/'
      path: '/'
      fullPath: '/orgs/$orgSlug/projects/$slug/settings/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/'
      path: '/'
      fullPath: '/orgs/$orgSlug/projects/$slug/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRoute
    }
    '/_authed/orgs/$orgSlug/settings/templates/blocks/$blockKey': {
      id: '/_authed/orgs/$orgSlug/settings/templates/blocks/$blockKey'
      path: '/templates/blocks/$blockKey'
      fullPath: '/orgs/$orgSlug/settings/templates/blocks/$blockKey'
      preLoaderRoute: typeof AuthedOrgsOrgSlugSettingsTemplatesBlocksBlockKeyRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/tickets/$id': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/orgs/$orgSlug/projects/$slug/tickets/$id'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugTicketsIdRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/settings/workflow': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/settings/workflow'
      path: '/workflow'
      fullPath: '/orgs/$orgSlug/projects/$slug/settings/workflow'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/settings/team': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/settings/team'
      path: '/team'
      fullPath: '/orgs/$orgSlug/projects/$slug/settings/team'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsTeamRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/settings/integrations': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/settings/integrations'
      path: '/integrations'
      fullPath: '/orgs/$orgSlug/projects/$slug/settings/integrations'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/settings/general': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/settings/general'
      path: '/general'
      fullPath: '/orgs/$orgSlug/projects/$slug/settings/general'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/about': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/about'
      path: '/about'
      fullPath: '/orgs/$orgSlug/projects/$slug/about'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderAboutRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/sprints': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/sprints'
      path: '/sprints'
      fullPath: '/orgs/$orgSlug/projects/$slug/sprints'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/settings/templates/': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/settings/templates/'
      path: '/templates'
      fullPath: '/orgs/$orgSlug/projects/$slug/settings/templates/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/sprints/': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/sprints/'
      path: '/'
      fullPath: '/orgs/$orgSlug/projects/$slug/sprints/'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsIndexRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/tickets/$id_/split': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/tickets/$id_/split'
      path: '/tickets/$id/split'
      fullPath: '/orgs/$orgSlug/projects/$slug/tickets/$id/split'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugTicketsIdSplitRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/settings/templates/$templateKey': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/settings/templates/$templateKey'
      path: '/templates/$templateKey'
      fullPath: '/orgs/$orgSlug/projects/$slug/settings/templates/$templateKey'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesTemplateKeyRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/sprints/$groupId': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/_projectHeader/sprints/$groupId'
      path: '/$groupId'
      fullPath: '/orgs/$orgSlug/projects/$slug/sprints/$groupId'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsGroupIdRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRoute
    }
    '/_authed/orgs/$orgSlug/projects/$slug/settings/templates/blocks/$blockKey': {
      id: '/_authed/orgs/$orgSlug/projects/$slug/settings/templates/blocks/$blockKey'
      path: '/templates/blocks/$blockKey'
      fullPath: '/orgs/$orgSlug/projects/$slug/settings/templates/blocks/$blockKey'
      preLoaderRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesBlocksBlockKeyRouteImport
      parentRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute
    }
  }
}

interface AuthedOrgsOrgSlugSettingsRouteRouteChildren {
  AuthedOrgsOrgSlugSettingsAttachmentsRoute: typeof AuthedOrgsOrgSlugSettingsAttachmentsRoute
  AuthedOrgsOrgSlugSettingsDangerRoute: typeof AuthedOrgsOrgSlugSettingsDangerRoute
  AuthedOrgsOrgSlugSettingsGeneralRoute: typeof AuthedOrgsOrgSlugSettingsGeneralRoute
  AuthedOrgsOrgSlugSettingsMembersRoute: typeof AuthedOrgsOrgSlugSettingsMembersRoute
  AuthedOrgsOrgSlugSettingsStorageRoute: typeof AuthedOrgsOrgSlugSettingsStorageRoute
  AuthedOrgsOrgSlugSettingsIndexRoute: typeof AuthedOrgsOrgSlugSettingsIndexRoute
  AuthedOrgsOrgSlugSettingsTemplatesTemplateKeyRoute: typeof AuthedOrgsOrgSlugSettingsTemplatesTemplateKeyRoute
  AuthedOrgsOrgSlugSettingsTemplatesIndexRoute: typeof AuthedOrgsOrgSlugSettingsTemplatesIndexRoute
  AuthedOrgsOrgSlugSettingsTemplatesBlocksBlockKeyRoute: typeof AuthedOrgsOrgSlugSettingsTemplatesBlocksBlockKeyRoute
}

const AuthedOrgsOrgSlugSettingsRouteRouteChildren: AuthedOrgsOrgSlugSettingsRouteRouteChildren =
  {
    AuthedOrgsOrgSlugSettingsAttachmentsRoute:
      AuthedOrgsOrgSlugSettingsAttachmentsRoute,
    AuthedOrgsOrgSlugSettingsDangerRoute: AuthedOrgsOrgSlugSettingsDangerRoute,
    AuthedOrgsOrgSlugSettingsGeneralRoute:
      AuthedOrgsOrgSlugSettingsGeneralRoute,
    AuthedOrgsOrgSlugSettingsMembersRoute:
      AuthedOrgsOrgSlugSettingsMembersRoute,
    AuthedOrgsOrgSlugSettingsStorageRoute:
      AuthedOrgsOrgSlugSettingsStorageRoute,
    AuthedOrgsOrgSlugSettingsIndexRoute: AuthedOrgsOrgSlugSettingsIndexRoute,
    AuthedOrgsOrgSlugSettingsTemplatesTemplateKeyRoute:
      AuthedOrgsOrgSlugSettingsTemplatesTemplateKeyRoute,
    AuthedOrgsOrgSlugSettingsTemplatesIndexRoute:
      AuthedOrgsOrgSlugSettingsTemplatesIndexRoute,
    AuthedOrgsOrgSlugSettingsTemplatesBlocksBlockKeyRoute:
      AuthedOrgsOrgSlugSettingsTemplatesBlocksBlockKeyRoute,
  }

const AuthedOrgsOrgSlugSettingsRouteRouteWithChildren =
  AuthedOrgsOrgSlugSettingsRouteRoute._addFileChildren(
    AuthedOrgsOrgSlugSettingsRouteRouteChildren,
  )

interface AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRouteChildren {
  AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsGroupIdRoute: typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsGroupIdRoute
  AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsIndexRoute: typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsIndexRoute
}

const AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRouteChildren: AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRouteChildren =
  {
    AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsGroupIdRoute:
      AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsGroupIdRoute,
    AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsIndexRoute:
      AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsIndexRoute,
  }

const AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRouteWithChildren =
  AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRoute._addFileChildren(
    AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRouteChildren,
  )

interface AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRouteChildren {
  AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRoute: typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRouteWithChildren
  AuthedOrgsOrgSlugProjectsSlugProjectHeaderAboutRoute: typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderAboutRoute
  AuthedOrgsOrgSlugProjectsSlugProjectHeaderIndexRoute: typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderIndexRoute
}

const AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRouteChildren: AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRouteChildren =
  {
    AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRoute:
      AuthedOrgsOrgSlugProjectsSlugProjectHeaderSprintsRouteRouteWithChildren,
    AuthedOrgsOrgSlugProjectsSlugProjectHeaderAboutRoute:
      AuthedOrgsOrgSlugProjectsSlugProjectHeaderAboutRoute,
    AuthedOrgsOrgSlugProjectsSlugProjectHeaderIndexRoute:
      AuthedOrgsOrgSlugProjectsSlugProjectHeaderIndexRoute,
  }

const AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRouteWithChildren =
  AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRoute._addFileChildren(
    AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRouteChildren,
  )

interface AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteChildren {
  AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRoute
  AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRoute
  AuthedOrgsOrgSlugProjectsSlugSettingsTeamRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsTeamRoute
  AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRoute
  AuthedOrgsOrgSlugProjectsSlugSettingsIndexRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsIndexRoute
  AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesTemplateKeyRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesTemplateKeyRoute
  AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesIndexRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesIndexRoute
  AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesBlocksBlockKeyRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesBlocksBlockKeyRoute
}

const AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteChildren: AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteChildren =
  {
    AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRoute:
      AuthedOrgsOrgSlugProjectsSlugSettingsGeneralRoute,
    AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRoute:
      AuthedOrgsOrgSlugProjectsSlugSettingsIntegrationsRoute,
    AuthedOrgsOrgSlugProjectsSlugSettingsTeamRoute:
      AuthedOrgsOrgSlugProjectsSlugSettingsTeamRoute,
    AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRoute:
      AuthedOrgsOrgSlugProjectsSlugSettingsWorkflowRoute,
    AuthedOrgsOrgSlugProjectsSlugSettingsIndexRoute:
      AuthedOrgsOrgSlugProjectsSlugSettingsIndexRoute,
    AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesTemplateKeyRoute:
      AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesTemplateKeyRoute,
    AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesIndexRoute:
      AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesIndexRoute,
    AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesBlocksBlockKeyRoute:
      AuthedOrgsOrgSlugProjectsSlugSettingsTemplatesBlocksBlockKeyRoute,
  }

const AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteWithChildren =
  AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute._addFileChildren(
    AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteChildren,
  )

interface AuthedOrgsOrgSlugProjectsSlugRouteRouteChildren {
  AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRoute: typeof AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRouteWithChildren
  AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute: typeof AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteWithChildren
  AuthedOrgsOrgSlugProjectsSlugTicketsIdRoute: typeof AuthedOrgsOrgSlugProjectsSlugTicketsIdRoute
  AuthedOrgsOrgSlugProjectsSlugTicketsIdSplitRoute: typeof AuthedOrgsOrgSlugProjectsSlugTicketsIdSplitRoute
}

const AuthedOrgsOrgSlugProjectsSlugRouteRouteChildren: AuthedOrgsOrgSlugProjectsSlugRouteRouteChildren =
  {
    AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRoute:
      AuthedOrgsOrgSlugProjectsSlugProjectHeaderRouteRouteWithChildren,
    AuthedOrgsOrgSlugProjectsSlugSettingsRouteRoute:
      AuthedOrgsOrgSlugProjectsSlugSettingsRouteRouteWithChildren,
    AuthedOrgsOrgSlugProjectsSlugTicketsIdRoute:
      AuthedOrgsOrgSlugProjectsSlugTicketsIdRoute,
    AuthedOrgsOrgSlugProjectsSlugTicketsIdSplitRoute:
      AuthedOrgsOrgSlugProjectsSlugTicketsIdSplitRoute,
  }

const AuthedOrgsOrgSlugProjectsSlugRouteRouteWithChildren =
  AuthedOrgsOrgSlugProjectsSlugRouteRoute._addFileChildren(
    AuthedOrgsOrgSlugProjectsSlugRouteRouteChildren,
  )

interface AuthedOrgsOrgSlugRouteRouteChildren {
  AuthedOrgsOrgSlugSettingsRouteRoute: typeof AuthedOrgsOrgSlugSettingsRouteRouteWithChildren
  AuthedOrgsOrgSlugIndexRoute: typeof AuthedOrgsOrgSlugIndexRoute
  AuthedOrgsOrgSlugProjectsSlugRouteRoute: typeof AuthedOrgsOrgSlugProjectsSlugRouteRouteWithChildren
  AuthedOrgsOrgSlugProjectsIndexRoute: typeof AuthedOrgsOrgSlugProjectsIndexRoute
}

const AuthedOrgsOrgSlugRouteRouteChildren: AuthedOrgsOrgSlugRouteRouteChildren =
  {
    AuthedOrgsOrgSlugSettingsRouteRoute:
      AuthedOrgsOrgSlugSettingsRouteRouteWithChildren,
    AuthedOrgsOrgSlugIndexRoute: AuthedOrgsOrgSlugIndexRoute,
    AuthedOrgsOrgSlugProjectsSlugRouteRoute:
      AuthedOrgsOrgSlugProjectsSlugRouteRouteWithChildren,
    AuthedOrgsOrgSlugProjectsIndexRoute: AuthedOrgsOrgSlugProjectsIndexRoute,
  }

const AuthedOrgsOrgSlugRouteRouteWithChildren =
  AuthedOrgsOrgSlugRouteRoute._addFileChildren(
    AuthedOrgsOrgSlugRouteRouteChildren,
  )

interface AuthedRouteRouteChildren {
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedOrgsOrgSlugRouteRoute: typeof AuthedOrgsOrgSlugRouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedOrgsOrgSlugRouteRoute: AuthedOrgsOrgSlugRouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  publicLoginRoute: publicLoginRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
  publicOauthConsentRoute: publicOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
